### Request Astik
POST http://localhost:5000/api/login
Content-Type: application/json
Token: abasdfd
Cookie: token=tata; tata=maga

{
    "userName": "ruet_cse",
    "email": "d.jango@gmail.com",
    "password": "cseruet#@12B"
}

# buet_cse
# cse_buet@gmail.com
# csebuet#@12B

# ruet_cse
# cse_ruet@gmail.com
# cseruet#@12B