### Request Astik
GET http://localhost:5000/
Content-Type: application/json
Token: abasdfd

{
    "userName": "DJango",
    "email": "d.jango@gmail.com",
    "password": "djagoPy123#"
}

# buet_cse
# cse_buet@gmail.com
# csebuet#@12B